quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Never"
indent_type = "Tabs"
indent_width = 4
column_width = 2000
line_endings = "Windows"

[sort_requires]
enabled = true
